default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: bebopvinh
  password: Rails.application.credentials.dig(:postgres, :password)
development:
  <<: *default
  database: developmentdb

# test:
#   <<: *default
#   database: learn-collective_test

production:
  <<: *default
  database: productiondb
