default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: learn-collective_development

test:
  <<: *default
  database: learn-collective_test

production:
  <<: *default
  database: learn-collective_production
  username: learn-collective
  password: <%= ENV['LEARN-COLLECTIVE_DATABASE_PASSWORD'] %>
